image: "golang:1.13"


before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$GOVKAPI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - git config --global user.email "cicd-go-vkapi-gen@gitlab.com"
  - git config --global user.name "CIDI GO VK API Generator"

stages:
  - test
  - deploy

job 1:
  stage: test
  script: go test

job 2:
  stage: deploy
  script: /bin/bash build_deploy.sh
